<?php
$now = $_COOKIE['lang'] == "PT" ? "Agora" : "Now";
$revenue = $_COOKIE['lang'] == "PT" ? "Receitas" : "Revenues";
$expense = $_COOKIE['lang'] == "PT" ? "Despesas" : "Expenses";
$home = $_COOKIE['lang'] == "PT" ? "Início" : "Home";
$monthly_comparison = $_COOKIE['lang'] == "PT" ? "Comparação Mensal" : "Monthly Comparison";
$year_comparison = $_COOKIE['lang'] == "PT" ? "Comparação Anual" : "Year Comparison";
$monthly_summary = $_COOKIE['lang'] == "PT" ? "Sumário Mensal" : "Monthly Summary";
$accounts = $_COOKIE['lang'] == "PT" ? "Contas" : "Accounts";
$account = $_COOKIE['lang'] == "PT" ? "Conta" : "Account";
$debts = $_COOKIE['lang'] == "PT" ? "Dívidas" : "Debts";
$categories_expenses =  $_COOKIE['lang'] == "PT" ? "Categorias Despesas" : "Categories Expenses";
$name_translate_pt =  $_COOKIE['lang'] == "PT" ? "Nome PT" : "Name PT";
$name_translate_en =  $_COOKIE['lang'] == "PT" ? "Nome EN" : "Name EN";
$edit_share =  $_COOKIE['lang'] == "PT" ? "Editar Partilha" : "Edit Share";
$add_debt = $_COOKIE['lang'] == "PT" ? "Adicionar Dívida" : "Add Debt";
$creditor = $_COOKIE['lang'] == "PT" ? "Credor" : "Creditor";
$installment = $_COOKIE['lang'] == "PT" ? "Parcelamento" : "Installment";
$paid_value = $_COOKIE['lang'] == "PT" ? "Valor Pago" : "Paid Value";
$summary_debts = $_COOKIE['lang'] == "PT" ? "Resumo de Dívidas" : "Summary of Debts";
$due_date = $_COOKIE['lang'] == "PT" ? "Data de Vencimento" : "Due Date";
$manage_loans = $_COOKIE['lang'] == "PT" ? "Gerir Empréstimos" : "Manage Loans";
$add_loan = $_COOKIE['lang'] == "PT" ? "Adicionar Empréstimo" : "Add Loan";
$compound_interest = $_COOKIE['lang'] == "PT" ? "Juros Compostos" : "Compound Interest";
$financial_institution = $_COOKIE['lang'] == "PT" ? "Instituiçao Financeira" : "Financial Institution";
$amount_borrowed = $_COOKIE['lang'] == "PT" ? "Valor Emprestado" : "Amount Borrowed";
$loans = $_COOKIE['lang'] == "PT" ? "Empréstimos" : "Loans";
$goal = $_COOKIE['lang'] == "PT" ? "Meta" : "Goal";
$edit_debt = $_COOKIE['lang'] == "PT" ? "Editar Dívida" : "Edit Debt";
$manage_debts = $_COOKIE['lang'] == "PT" ? "Gerir Dívidas" : "Manage Debts";
$value_installments =  $_COOKIE['lang'] == "PT" ? "Valor da Parcela" : "Installment Amount";
$number_installments = $_COOKIE['lang'] == "PT" ? "Número de Parcelas" : "Number of Installmets";
$only_owner_can_delete = $_COOKIE['lang'] == "PT" ? "Apenas o Criador da Conta pode Deletar esta Conta!" : "Only the Creator of the Account can Delete this Account!";
$no = $_COOKIE['lang'] == "PT" ? "Sem" : "No";
$payment_control = $_COOKIE['lang'] == "PT" ? "Controle de Pagamento" : "Payment Control";
$account_deleted = $_COOKIE['lang'] == "PT" ? "Conta Deletada com Sucesso!" : "Account Successfully Deleted!";
$mensage =  $_COOKIE['lang'] == "PT" ? "Mensagem" : "Mensage";
$added = $_COOKIE['lang'] == "PT" ? "Adicionados" : "Added";
$share = $_COOKIE['lang'] == "PT" ? "Partilhar" : "Share";
$period = $_COOKIE['lang'] == "PT" ? "Período de Tempo" : "Time Period";
$friends = $_COOKIE['lang'] == "PT" ? "Amigos" : "Friends";
$rate = $_COOKIE['lang'] == "PT" ? "Taxa" : "Rate";
$today = $_COOKIE['lang'] == "PT" ? "Hoje" : "Today";
$years = $_COOKIE['lang'] == "PT" ? "Anos" : "Years";
$friend = $_COOKIE['lang'] == "PT" ? "Amigo" : "Friend";
$last_15_transactions = $_COOKIE['lang'] == "PT" ? "Últimas 15 transações" : "Last 15 Transactions";
$values = $_COOKIE['lang'] == "PT" ? "Valores" : "Values";
$scheduled_date = $_COOKIE['lang'] == "PT" ? "Data Agendada" : "Scheduled Date";
$schedule_expense = $_COOKIE['lang'] == "PT" ? "Agendar Despesa" : "Schedule Expense";
$scheduled_expenses = $_COOKIE['lang'] == "PT" ? "Despesas Agendadas" : "Scheduled Expenses";
$currency_converter = $_COOKIE['lang'] == "PT" ? "Convesor de Moedas" : "Currency Converter";
$initial_investment = $_COOKIE['lang'] == "PT" ? "Investimento Inicial" : "Initial Investment";
$compound_interest = $_COOKIE['lang'] == "PT" ? "Juros Compostos" : "Compound Interest";
$notifications = $_COOKIE['lang'] == "PT" ? "Notificaticações" : "Notifications";
$convertValue = $_COOKIE['lang'] == "PT" ? "Valor Convertido" : "Convert Value";
$convert = $_COOKIE['lang'] == "PT" ? "Converter" : "Convert";
$percentage = $_COOKIE['lang'] == "PT" ? "Percentagem" : "Percentage";
$expenses_summary = $_COOKIE['lang'] == "PT" ? "Sumário de Despesas" : "Expenses Summary";
$add_limit = $_COOKIE['lang'] == "PT" ? "Adicionar Orçamento" : "Add Budget";
$add_friend = $_COOKIE['lang'] == "PT" ? "Adicionar Amigo" : "Add Friend";
$your = $_COOKIE['lang'] == "PT" ? "Seu" : "Your";
$create_reminder = $_COOKIE['lang'] == "PT" ? "Criar Lembrete" : "Create Reminder";
$reinforcement = $_COOKIE['lang'] == "PT" ? "Reforço" : "Reinforcement";
$search = $_COOKIE['lang'] == "PT" ? "Procurar" : "Search";
$not_found = $_COOKIE['lang'] == "PT" ? "Utilizador não encontrado" : "Not Found User";
$financial_goals = $_COOKIE['lang'] == "PT" ? "Metas Financeiras" : "Financial Goals";
$financial_goal = $_COOKIE['lang'] == "PT" ? "Meta Financeira" : "Financial Goal";
$send_request = $_COOKIE['lang'] == "PT" ? "Enviar Pedido" : "Send Request";
$modal_friend = $_COOKIE['lang'] == "PT" ? "Deseja Remover Este Amigo" : "Want to Remove This Friend";
$max_translate = $_COOKIE['lang'] == "PT" ? "Máximo" : "Max";
$status_translate = $_COOKIE['lang'] == "PT" ? "Estado" : "Status";
$add_line = $_COOKIE['lang'] == "PT" ? "Adicionar Linha" : "Add Line";
$coin_translate = $_COOKIE['lang'] == "PT" ? "Moeda" : "Coin";
$received_request = $_COOKIE['lang'] == "PT" ? "Nenhum Pedido Recebido" : "No Friend Requests";
$sended_request = $_COOKIE['lang'] == "PT" ? "Nenhum Pedido Enviado" : "No Friend Sended";
$share_requests = $_COOKIE['lang'] == "PT" ? "Pedidos de Partilha" : "Share Requests";
$requests = $_COOKIE['lang'] == "PT" ? "Partilhas" : "Requests";
$user_friend = $_COOKIE['lang'] == "PT" ? "Esse Utilizador já está adicionado" : "This User is already added";
$add_financial_goals = $_COOKIE['lang'] == "PT" ? "Adicionar Metas Financeiras" : "Add Financial Goals";
$add_financial_goal = $_COOKIE['lang'] == "PT" ? "Adicionar Meta Financeira" : "Add Financial Goal";
$alert_limits = $_COOKIE['lang'] == "PT" ? "Tem Duas ou Mais Categorias Iguais" : "Have Two or More Equal Categories";
$view_limits = $_COOKIE['lang'] == "PT" ? "Ver Orçamentos" : "View Budgets";
$manage_limits = $_COOKIE['lang'] == "PT" ? "Gerir Orçamentos" : "Manage Budgets";
$manage_financial_goals = $_COOKIE['lang'] == "PT" ? "Gerir Metas Financeiras" : "Manage Financial Goals";
$create_account = $_COOKIE['lang'] == "PT" ? "Criar Conta" : "Create Account";
$manage_account = $_COOKIE['lang'] == "PT" ? "Gerir Contas" : "Manage Accounts";
$goals = $_COOKIE['lang'] == "PT" ? "Objetivos" : "Objectives";
$create_objective = $_COOKIE['lang'] == "PT" ? "Criar Objetivo" : "Create Objective";
$manage_goals = $_COOKIE['lang'] == "PT" ? "Gerir Objetivos" : "Manage Objectives";
$investing = $_COOKIE['lang'] == "PT" ? "Investir no Objetivo" : "Investing In Objetive";
$limit_translate = $_COOKIE['lang'] == "PT" ? "Orçamento" : "Budget";
$transactions = $_COOKIE['lang'] == "PT" ? "Transações" : "Transactions";
$new_expense = $_COOKIE['lang'] == "PT" ? "Nova Despesa" : "New expense";
$new_revenue = $_COOKIE['lang'] == "PT" ? "Nova Receita" : "New Revenue";
$manage_transaction = $_COOKIE['lang'] == "PT" ? "Gerir Transações" : "Manage Transactions";
$settings = $_COOKIE['lang'] == "PT" ? "Definições" : "Settings";
$limits = $_COOKIE['lang'] == "PT" ? "Orçamentos" : "Budgets";
$lights = $_COOKIE['lang'] == "PT" ? "Luzes" : "Lights";
$tools = $_COOKIE['lang'] == "PT" ? "Ferramentas" : "Tools";
$date_format = $_COOKIE['lang'] == "PT" ? "(A-m)" : "(Y-m)";
$daily_budgets = $_COOKIE['lang'] == "PT" ? "Orçamentos Diários" : "Daily Budgets";
$weekly_budgets = $_COOKIE['lang'] == "PT" ? "Orçamentos Semanais" : "Weekly Budgets";
$monthly_budgets = $_COOKIE['lang'] == "PT" ? "Orçamentos Mensais" : "Monthly Budgets";
$annual_budgets = $_COOKIE['lang'] == "PT" ? "Orçamentos Anuais" : "Annual Budgets";
$priority_translate = $_COOKIE['lang'] == "PT" ? "Prioridade" : "Priority";
$earnings = $_COOKIE['lang'] == "PT" ? "Ganhos (Sempre)" : "Earnings (Lifetime)";
$earnings_this_year = $_COOKIE['lang'] == "PT" ? "Ganhos (Este Ano)" : "Earnings (This Year)";
$expenses_translate = $_COOKIE['lang'] == "PT" ? "Despesas (Sempre)" : "Expenses (Lifetime)";
$current = $_COOKIE['lang'] == "PT" ? "(Atual)" : "(Current)";
$line_graph = $_COOKIE['lang'] == "PT" ? "Gráfico de Linhas" : "Line Graph";
$add_expense = $_COOKIE['lang'] == "PT" ? "Adicionar Despesa" : "Add Expense";
$add_revenue = $_COOKIE['lang'] == "PT" ? "Adicionar Receita" : "Add Revenue";
$category = $_COOKIE['lang'] == "PT" ? "Categoria" : "Category";
$value = $_COOKIE['lang'] == "PT" ? "Valor" : "Value";
$type_translate = $_COOKIE['lang'] == "PT" ? "Tipo" : "Type";
$date = $_COOKIE['lang'] == "PT" ? "Data" : "Date";
$this_week = $_COOKIE['lang'] == "PT" ? "Esta Semana" : "This Week";
$this_month = $_COOKIE['lang'] == "PT" ? "Este Mês" : "This Month";
$create_new_acc = $_COOKIE['lang'] == "PT" ? "Criar Nova Conta" : "Create New Account";
$name = $_COOKIE['lang'] == "PT" ? "Nome" : "Name";
$intial_cash = $_COOKIE['lang'] == "PT" ? "Dinheiro Inicial" : "Initial Cash";
$bar_graph = $_COOKIE['lang'] == "PT" ? "Gráfico de Barra" : "Bar Graph";
$summary = $_COOKIE['lang'] == "PT" ? "Sumário" : "Summary";
$edit = $_COOKIE['lang'] == "PT" ? "Editar" : "Edit";
$delete = $_COOKIE['lang'] == "PT" ? "Apagar" : "Delete";
$type[0] = $_COOKIE['lang'] == "PT" ? "Despesa" : "Expense";
$type[1] = $_COOKIE['lang'] == "PT" ? "Receita" : "Revenue";
$cash_translate = $_COOKIE['lang'] == "PT" ? "Dinheiro" : "Cash";
$create_new_objective = $_COOKIE['lang'] == "PT" ? "Criar Novo Objetivo" : "Create New Objective";
$objective_value = $_COOKIE['lang'] == "PT" ? "Valor Do Objetivo" : "Objective Value";
$missing_money = $_COOKIE['lang'] == "PT" ? "Dinheiro Em Falta" : "Missing Money";
$money_invested = $_COOKIE['lang'] == "PT" ? "Dinheiro Investido" : "Money Invested";
$progress = $_COOKIE['lang'] == "PT" ? "Progresso (Em Percentagem)" : "Progess (In Percentage)";
$objective = $_COOKIE['lang'] == "PT" ? "Objetivo" : "Objective";
$investing_in_the_objective = $_COOKIE['lang'] == "PT" ? "Investir no Objetivo" : "Investing In The Objective";
$description = $_COOKIE['lang'] == "PT" ? "Descrição" : "Description";
$to = $_COOKIE['lang'] == 'PT' ? "Para" : "To";
$optional = $_COOKIE['lang'] == 'PT' ? "Opcional" : "Optional";
$view = $_COOKIE['lang'] == 'PT' ? "Ver" : "View";
$from = $_COOKIE['lang'] == 'PT' ? "De" : "From";
$confirm = $_COOKIE['lang'] == 'PT' ? "Confirmar" : "Confirm";
$decline = $_COOKIE['lang'] == 'PT' ? "Recusar" : "Decline";
$transaction_translate = $_COOKIE['lang'] == 'PT' ? "Transação" : "Transaction";
$modal = $_COOKIE['lang'] == 'PT' ? "Deseja deletar esta transação" : "You want to delete this transaction";
$modal_financial_goal = $_COOKIE['lang'] == 'PT' ? "Deseja deletar esta meta financeira" : "You want to delete this financial goal";
$edit_financial_goal = $_COOKIE['lang'] == 'PT' ? "Editar Meta Financeira" : "Edit Financial Goal";
$register = $_COOKIE['lang'] == 'PT' ? "REGISTAR" : "REGISTER";
$password_translate = $_COOKIE['lang'] == 'PT' ? "PALAVRA-PASSE" : "PASSWORD";
$login = $_COOKIE['lang'] == 'PT' ? "ENTRAR" : "LOGIN";
$have_forgot_pass = $_COOKIE['lang'] == 'PT' ? "ESQUECEU A SUA PALAVRA-PASSE?" : "HAVE YOU FORGOTTEN YOUR PASSWORD";
$create_account_log = $_COOKIE['lang'] == 'PT' ? "CRIAR CONTA" : "CREATE ACCOUNT";
$name_sing = $_COOKIE['lang'] == 'PT' ? "NOME" : "NAME";
$update_check = $_COOKIE['lang'] == 'PT' ? "OS SEUS DADOS FORAM ATUALIZADOS COM SUCESSO!" : "YOUR DATA HAS BEEN SUCCESSFULLY UPDATED!";
$personal_details = $_COOKIE['lang'] == 'PT' ? "Detalhes Pessoais" : "Personal Details";
$password_translate_set = $_COOKIE['lang'] == 'PT' ? "Palavra-Passe" : "Password";
$update_translate = $_COOKIE['lang'] == 'PT' ? "Atualizar" : "Update";
$initial_date_translate = $_COOKIE['lang'] == 'PT' ? "Data Inicial" : "Initial Date";
$final_date_translate = $_COOKIE['lang'] == 'PT' ? "Data Final" : "Final Date";
$verify = $_COOKIE['lang'] == 'PT' ? "Verificador de" : "Verify";
$shares = $_COOKIE['lang'] == 'PT' ? "Partilhas" : "Shares";
$shared_accounts = $_COOKIE['lang'] == 'PT' ? "Contas Partilhadas" : "Shared Accounts";
$shared_objectives = $_COOKIE['lang'] == 'PT' ? "Objetivos Partilhados" : "Shared Objectives";
$modal_account_shared = $_COOKIE['lang'] == 'PT' ? "Deseja Remover Esta Partilha de Conta" : "Do You Want to Remove This Account Share";
$modal_financial_goal_shared = $_COOKIE['lang'] == 'PT' ? "Deseja Remover Esta Partilha de Meta Financeira" : "Do You Want to Remove This Financial Goal Share";
$shared_financial_goals = $_COOKIE['lang'] == 'PT' ? "Metas Financeiras Partilhadas" : "Shared Financial Goals";
$modal_objetive_shared = $_COOKIE['lang'] == 'PT' ? "Deseja Remover Esta Partilha de Objetivo" : "Do You Want to Remove This Goal Share";
$modal_acc = $_COOKIE['lang'] == 'PT' ? "Deseja Apagar esta conta" : "Do you want to Delete this account";
$modal_limit = $_COOKIE['lang'] == 'PT' ? "Deseja Apagar este orçamento" : "Do you want to Delete this budget";
$modal_acc2 = $_COOKIE['lang'] == 'PT' ? "Ao fazê-lo, todas as transações desta conta serão eliminadas e irá alterar o seu saldo total." : "By doing so, all transactions from this account will be deleted and you will change your total balance.";
$welcome = $_COOKIE['lang'] == 'PT' ? "Bem-Vindo" : "Welcome";
$expense_translate = $_COOKIE['lang'] == 'PT' ? "Gasto" : "Expense";
$share_question = $_COOKIE['lang'] == 'PT' ? "O que Deseja Partilhar?" : "What do You Want to Share?";
$light = $_COOKIE['lang'] == 'PT' ? "Claro" : "Light";
$dark = $_COOKIE['lang'] == 'PT' ? "Escuro" : "Dark";
$calculate = $_COOKIE['lang'] == 'PT' ? "Calcular" : "Calculate";
$total_value = $_COOKIE['lang'] == 'PT' ? "Valor Total" : "Total Value";
$completed_objectives = $_COOKIE['lang'] == 'PT' ? "Objetivos Concluídos" : "Completed Objectives";
$total_remaining = $_COOKIE['lang'] == 'PT' ? "Total Restante" : "Total Remaining";
$modal_objetive = $_COOKIE['lang'] == 'PT' ? "Deseja deletar este objetivo" : "You want to delete this objetive";
$objetive = $_COOKIE['lang'] == 'PT' ? "Objetivo" : "Objective";
$redeem = $_COOKIE['lang'] == 'PT' ? "Resgatar" : "Redeem";
$expense_manager = $_COOKIE['lang'] == 'PT' ? "Gestor de despesas" : "Expense Manager";
$this_year = $_COOKIE['lang'] == 'PT' ? "Este Ano" : "This Year";
$proof_of_payment = $_COOKIE['lang'] == 'PT' ? "Comprovante" : "Proof of Payment";
$description = $_COOKIE['lang'] == 'PT' ? "Descrição" : "Description";
